apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-set
  labels:
   name: monitor 
spec:
 selector:
  matchLabels:
   name: monitor 
 template:
  metadata:
   labels:
    name: monitor 
  spec:
   containers:
    - name: monitor 
      image: gcr.io/google-containers/fluentd-elasticsearch:1.20
