apiVersion: v1
kind: Service
metadata:
 name: r-m-s
 labels:
  app: redis
  env: back
  type: master
spec:
 selector:
   app: redis
   env: back
   type: master
 type: ClusterIP
 ports:
  - port: 6379
    targetPort: 6379
