apiVersion: apps/v1
kind: Deployment 
metadata:
 name: nginx-deploy
 labels:
  app: nginx-app
spec:
 replicas: 1
 selector:
  matchLabels:
   app: nginx-app
 template:
   metadata:
    name: nginx-pod
    labels:
      app: nginx-app
   spec:
     containers:
       - name: nginx-con
         image: nginx:1.7.9
         ports:
          - containerPort: 80
