apiVersion: apps/v1
kind: Deployment 
metadata:
 name: nginx-deploy
 labels:
  app: nginx-app
spec:
 replicas: 1
 selector:
  matchLabels:
   app: nginx-app
   env: front
 template:
   metadata:
    name: nginx-pod
    labels:
      app: nginx-app
      env: front
   spec:
     containers:
       - name: nginx-con
         image: gcr.io/google-samples/gb-frontend:v4
         ports:
          - containerPort: 80
