apiVersion: v1
kind: ReplicationController
metadata:
 name: nginx-rc
spec:
 replicas: 2
 selector:
   app: nginx-app
 template:
   metadata:
    name: nginx-pod
    labels:
      app: nginx-app
   spec:
     containers:
       - name: nginx-con
         image: nginx 
         ports:
          - containerport: 80
