apiVersion: apps/v1
kind: Deployment 
metadata:
 name: redis-slave
 labels:
  app: redis
spec:
 replicas: 1
 selector:
  matchLabels:
   app: redis
   type: slave
   env: back
 template:
  metadata:
   labels:
    app: redis 
    type: slave
    env: back
  spec:
   containers:
    - name: slave
      image: gcr.io/google_samples/gb-redisslave:v1
      ports:
       - containerPort: 6379
