apiVersion: v1
kind: Service
metadata:
 name: r-s-s
 labels:
  app: redis
  env: back
  type: slave
spec:
 selector:
   app: redis
   env: back
   type: slave
 type: ClusterIP
 ports:
  - port: 6379
    
